spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}

bff:
  frontend:
    redirect-uri: ${BFF_FRONTEND_REDIRECT_URI}

  oauth2:
    authorization-uri: ${BFF_OAUTH2_AUTHORIZATION_URI}
    token-uri: ${BFF_OAUTH2_TOKEN_URI}
    userinfo-uri: ${BFF_OAUTH2_USERINFO_URI}
    client-id: ${BFF_CLIENT_ID}
    client-secret: ${BFF_CLIENT_SECRET}
    redirect-uri: ${BFF_OAUTH2_REDIRECT_URI}
    end-session-uri: ${BFF_OAUTH2_END_SESSION_URI}
    logout-uri: ${BFF_OAUTH2_LOGOUT_URI}
    scope: ${BFF_OAUTH2_SCOPE:openid profile}

  api:
    community-me-uri: ${BFF_API_COMMUNITY_ME_URI}
    user-me-uri: ${BFF_API_USER_ME_URI}
    user-signup-uri: ${BFF_API_USER_SIGNUP_URI}
    stock-me-uri: ${BFF_API_STOCK_ME_URI}

logging:
  level:
    com.springmsa.bff: info
