spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: redis
      port: 6379

bff:
  frontend:
    redirect-uri: ${BFF_FRONTEND_REDIRECT_URI:http://localhost:5173}

  oauth2:
    authorization-uri: ${BFF_OAUTH2_AUTHORIZATION_URI:http://localhost:8080/oauth2/authorize}
    token-uri: ${BFF_OAUTH2_TOKEN_URI:http://spring-cloud-gateway:8080/oauth2/token}
    userinfo-uri: ${BFF_OAUTH2_USERINFO_URI:http://spring-cloud-gateway:8080/userinfo}
    client-id: ${BFF_CLIENT_ID:bff-client}
    client-secret: ${BFF_CLIENT_SECRET:bff-secret}
    redirect-uri: ${BFF_OAUTH2_REDIRECT_URI:http://localhost:8080/bff/auth/callback}
    end-session-uri: ${BFF_OAUTH2_END_SESSION_URI:http://localhost:8080/connect/logout}
    logout-uri: ${BFF_OAUTH2_LOGOUT_URI:http://localhost:8080/logout}
    scope: ${BFF_OAUTH2_SCOPE:openid profile}

  api:
    community-me-uri: ${BFF_API_COMMUNITY_ME_URI:http://spring-cloud-gateway:8080/api/community/me}
    user-me-uri: ${BFF_API_USER_ME_URI:http://spring-cloud-gateway:8080/api/user/me}
    stock-me-uri: ${BFF_API_STOCK_ME_URI:http://spring-cloud-gateway:8080/api/stock/me}
