apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 12-stock-service.yaml
  - 40-web.yaml

replicas:
  - name: spring-member-stock-service
    count: 2
  - name: spring-member-stock-web
    count: 2

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {}
                matchLabelKeys:
                  - pod-template-hash
                topologyKey: kubernetes.io/hostname
