apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-msa-config
  namespace: spring-msa
data:
  POSTGRES_DB: msa
  POSTGRES_USER: msa
  PUBLIC_GATEWAY_URL: http://user.localtest.me
  SHELL_FRONTEND_URL: http://user.localtest.me
  ADMIN_FRONTEND_URL: http://admin.localtest.me
  TOSS_API_BASE_URL: https://openapi.tossinvest.com
