apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-msa-config
  namespace: spring-msa
data:
  STORAGE_HOST: 192.168.147.101
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  PUBLIC_GATEWAY_URL: http://user.localtest.me
  SHELL_FRONTEND_URL: http://user.localtest.me
  ADMIN_FRONTEND_URL: http://admin.localtest.me
  TOSS_API_BASE_URL: https://openapi.tossinvest.com
