apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-user-service
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-user-service
  template:
    metadata:
      labels:
        app: spring-user-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-user-service
          image: ghcr.io/hyunmyungchoi/spring-user-service:2b2ca329c24136c11cd668bc514f906a4b116e8f
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              value: "true"
            - name: SERVER_TOMCAT_ACCESSLOG_DIRECTORY
              value: /dev
            - name: SERVER_TOMCAT_ACCESSLOG_PREFIX
              value: stdout
            - name: SERVER_TOMCAT_ACCESSLOG_SUFFIX
              value: ""
            - name: SERVER_TOMCAT_ACCESSLOG_FILE_DATE_FORMAT
              value: ""
            - name: SERVER_TOMCAT_ACCESSLOG_BUFFERED
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/msa
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: spring-msa-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: REDIS_PASSWORD
            - name: SPRING_MSA_INTERNAL_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: SPRING_MSA_INTERNAL_API_TOKEN
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://user.localtest.me
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://spring-security-authorization-server:9000/oauth2/jwks
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
---
apiVersion: v1
kind: Service
metadata:
  name: spring-user-service
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-user-service
  ports:
    - port: 8081
      targetPort: 8081

