apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-member-stock-service
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-member-stock-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8084"
      labels:
        app: spring-member-stock-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-member-stock-service
          image: ghcr.io/hyunmyungchoi/spring-member-stock-service:906f5013d0356b93aead2e022337efa6085ed7b5
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              value: "true"
            - name: SERVER_TOMCAT_ACCESSLOG_DIRECTORY
              value: /dev
            - name: SERVER_TOMCAT_ACCESSLOG_PREFIX
              value: stdout
            - name: SERVER_TOMCAT_ACCESSLOG_SUFFIX
              value: ""
            - name: SERVER_TOMCAT_ACCESSLOG_FILE_DATE_FORMAT
              value: ""
            - name: SERVER_TOMCAT_ACCESSLOG_BUFFERED
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/msa
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: spring-msa-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: REDIS_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://user.localtest.me
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://spring-security-authorization-server:9000/oauth2/jwks
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
            - name: TOSS_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-msa-config
                  key: TOSS_API_BASE_URL
            - name: TOSS_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: TOSS_API_CLIENT_ID
            - name: TOSS_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: TOSS_API_CLIENT_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: spring-member-stock-service
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-member-stock-service
  ports:
    - port: 8084
      targetPort: 8084

