apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-member-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-member-web
  template:
    metadata:
      labels:
        app: spring-member-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-pool: application
      containers:
        - name: spring-member-web
          image: ghcr.io/hyunmyungchoi/spring-member-web@sha256:46d05830fe0164abdec974f1d81b8cd133d6afb8bb43b3257033d442c8d2ff8a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-member-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-member-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-member-community-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-member-community-web
  template:
    metadata:
      labels:
        app: spring-member-community-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-pool: application
      containers:
        - name: spring-member-community-web
          image: ghcr.io/hyunmyungchoi/spring-member-community-web@sha256:d1412063ed4238de6e44913796b272867fd8a86e9f2dccc78d622ef2f6d8ea13
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-member-community-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-member-community-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-member-stock-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-member-stock-web
  template:
    metadata:
      labels:
        app: spring-member-stock-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-pool: application
      containers:
        - name: spring-member-stock-web
          image: ghcr.io/hyunmyungchoi/spring-member-stock-web@sha256:0af02e2397730dace021578352b92dddc30a1b8189b1a13474d3458754747c3a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-member-stock-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-member-stock-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin-web
  template:
    metadata:
      labels:
        app: spring-admin-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-pool: application
      containers:
        - name: spring-admin-web
          image: ghcr.io/hyunmyungchoi/spring-admin-web@sha256:8eb90daee342bc7f6913825a1bd4d8a95876c93b4dc3b899ad3394a98f756be9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-admin-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin-users-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin-users-web
  template:
    metadata:
      labels:
        app: spring-admin-users-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-pool: application
      containers:
        - name: spring-admin-users-web
          image: ghcr.io/hyunmyungchoi/spring-admin-users-web@sha256:77c9aec41713de72cc85e0d04c24acea5037f7b90fea56c49728a84ac1a2423f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-users-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-admin-users-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin-logs-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin-logs-web
  template:
    metadata:
      labels:
        app: spring-admin-logs-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-pool: application
      containers:
        - name: spring-admin-logs-web
          image: ghcr.io/hyunmyungchoi/spring-admin-logs-web@sha256:9284c2efbbb475d46067924c9aabc960deba156f57f48c06371e0d8f44c1c216
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-logs-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-admin-logs-web
  ports:
    - port: 80
      targetPort: 80
