apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-member-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-member-web
  template:
    metadata:
      labels:
        app: spring-member-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-member-web
          image: ghcr.io/hyunmyungchoi/spring-member-web:efdfd894ddb21f69c7677456da246493b37a664c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-member-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-member-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-community-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-community-web
  template:
    metadata:
      labels:
        app: spring-community-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-community-web
          image: ghcr.io/hyunmyungchoi/spring-community-web:b59c2f252c78ebdaba53299871ff6d8bb09aefb6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-community-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-community-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-stock-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-stock-web
  template:
    metadata:
      labels:
        app: spring-stock-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-stock-web
          image: ghcr.io/hyunmyungchoi/spring-stock-web:efdfd894ddb21f69c7677456da246493b37a664c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-stock-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-stock-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin-web
  template:
    metadata:
      labels:
        app: spring-admin-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-admin-web
          image: ghcr.io/hyunmyungchoi/spring-admin-web:efdfd894ddb21f69c7677456da246493b37a664c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-admin-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin-users-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin-users-web
  template:
    metadata:
      labels:
        app: spring-admin-users-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-admin-users-web
          image: ghcr.io/hyunmyungchoi/spring-admin-users-web:efdfd894ddb21f69c7677456da246493b37a664c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-users-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-admin-users-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin-logs-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin-logs-web
  template:
    metadata:
      labels:
        app: spring-admin-logs-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-admin-logs-web
          image: ghcr.io/hyunmyungchoi/spring-admin-logs-web:efdfd894ddb21f69c7677456da246493b37a664c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-logs-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-admin-logs-web
  ports:
    - port: 80
      targetPort: 80
