apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-msa-user-bff-legacy-login
  namespace: spring-msa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /oauth2/authorization/member-bff
spec:
  ingressClassName: nginx
  rules:
    - host: user.localtest.me
      http:
        paths:
          - path: /bff/auth/login
            pathType: Exact
            backend:
              service:
                name: spring-member-bff-service
                port:
                  number: 8079
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-msa-user-bff-legacy-signup
  namespace: spring-msa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /registration/member
spec:
  ingressClassName: nginx
  rules:
    - host: user.localtest.me
      http:
        paths:
          - path: /bff/auth/signup
            pathType: Exact
            backend:
              service:
                name: spring-member-bff-service
                port:
                  number: 8079
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-msa-user-bff
  namespace: spring-msa
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: user.localtest.me
      http:
        paths:
          - path: /bff(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: spring-member-bff-service
                port:
                  number: 8079
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-msa-user
  namespace: spring-msa
spec:
  ingressClassName: nginx
  rules:
    - host: user.localtest.me
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: spring-member-gateway
                port:
                  number: 8080
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: spring-member-gateway
                port:
                  number: 8080
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: spring-member-gateway
                port:
                  number: 8080
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: spring-member-gateway
                port:
                  number: 8080
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: spring-member-gateway
                port:
                  number: 8080
          - path: /connect
            pathType: Prefix
            backend:
              service:
                name: spring-member-gateway
                port:
                  number: 8080
          - path: /userinfo
            pathType: Prefix
            backend:
              service:
                name: spring-member-gateway
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-member-web
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-msa-admin
  namespace: spring-msa
spec:
  ingressClassName: nginx
  rules:
    - host: admin.localtest.me
      http:
        paths:
          - path: /admin-bff
            pathType: Prefix
            backend:
              service:
                name: spring-admin-gateway
                port:
                  number: 8090
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: spring-admin-gateway
                port:
                  number: 8090
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: spring-admin-gateway
                port:
                  number: 8090
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: spring-admin-gateway
                port:
                  number: 8090
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: spring-admin-gateway
                port:
                  number: 8090
          - path: /connect
            pathType: Prefix
            backend:
              service:
                name: spring-admin-gateway
                port:
                  number: 8090
          - path: /userinfo
            pathType: Prefix
            backend:
              service:
                name: spring-admin-gateway
                port:
                  number: 8090
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-admin-web
                port:
                  number: 80
