apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-external-data-services.yaml
  - 10-user-service.yaml
  - 11-community-service.yaml
  - 12-stock-service.yaml
  - 13-auth-server.yaml
  - 20-member-bff-service.yaml
  - 21-admin-bff-service.yaml
  - 30-member-gateway.yaml
  - 31-admin-gateway.yaml
  - 40-web.yaml
  - 50-ingress.yaml

replicas:
  - name: spring-user-service
    count: 2
  - name: spring-member-community-service
    count: 2
  - name: spring-member-stock-service
    count: 2
  - name: spring-security-authorization-server
    count: 2
  - name: spring-member-bff-service
    count: 2
  - name: spring-admin-bff-service
    count: 2
  - name: spring-member-gateway
    count: 2
  - name: spring-admin-gateway
    count: 2
  - name: spring-member-web
    count: 2
  - name: spring-member-community-web
    count: 2
  - name: spring-member-stock-web
    count: 2
  - name: spring-admin-web
    count: 2
  - name: spring-admin-users-web
    count: 2
  - name: spring-admin-logs-web
    count: 2

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {}
                matchLabelKeys:
                  - pod-template-hash
                topologyKey: kubernetes.io/hostname
