apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-security-authorization-server
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-security-authorization-server
  template:
    metadata:
      labels:
        app: spring-security-authorization-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-security-authorization-server
          image: ghcr.io/hyunmyungchoi/spring-security-authorization-server:latest
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: REDIS_PASSWORD

            - name: AUTH_SERVER_ISSUER
              value: http://localhost:8080
            - name: USER_SERVICE_BASE_URL
              value: http://spring-user-service:8081

            - name: BFF_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-msa-oauth-secret
                  key: BFF_CLIENT_ID
            - name: BFF_CLIENT_SECRET_HASH
              valueFrom:
                secretKeyRef:
                  name: spring-msa-oauth-secret
                  key: BFF_CLIENT_SECRET_HASH
            - name: BFF_OAUTH2_REDIRECT_URI
              value: http://localhost:8080/bff/auth/callback
            - name: BFF_POST_LOGOUT_REDIRECT_URI
              value: http://localhost:5173/login

            - name: ADMIN_BFF_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-msa-oauth-secret
                  key: ADMIN_BFF_CLIENT_ID
            - name: ADMIN_BFF_CLIENT_SECRET_HASH
              valueFrom:
                secretKeyRef:
                  name: spring-msa-oauth-secret
                  key: ADMIN_BFF_CLIENT_SECRET_HASH
            - name: ADMIN_BFF_OAUTH2_REDIRECT_URI
              value: http://localhost:8090/admin-bff/auth/callback
            - name: ADMIN_BFF_POST_LOGOUT_REDIRECT_URI
              value: http://localhost:5176
            - name: ADMIN_BFF_POST_LOGOUT_LOGIN_REDIRECT_URI
              value: http://localhost:5176/login

---
apiVersion: v1
kind: Service
metadata:
  name: spring-security-authorization-server
  namespace: spring-msa
spec:
  selector:
    app: spring-security-authorization-server
  ports:
    - port: 9000
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-bff-service
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-bff-service
  template:
    metadata:
      labels:
        app: spring-bff-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-bff-service
          image: ghcr.io/hyunmyungchoi/spring-bff-service:latest
          ports:
            - containerPort: 8079
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod

            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-msa-secret
                  key: REDIS_PASSWORD

            - name: BFF_FRONTEND_REDIRECT_URI
              value: http://localhost:5173

            - name: BFF_OAUTH2_AUTHORIZATION_URI
              value: http://localhost:8080/oauth2/authorize
            - name: BFF_OAUTH2_TOKEN_URI
              value: http://spring-cloud-gateway:8080/oauth2/token
            - name: BFF_OAUTH2_USERINFO_URI
              value: http://spring-cloud-gateway:8080/userinfo
            - name: BFF_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: spring-msa-oauth-secret
                  key: BFF_CLIENT_ID
            - name: BFF_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-msa-oauth-secret
                  key: BFF_CLIENT_SECRET
            - name: BFF_OAUTH2_REDIRECT_URI
              value: http://localhost:8080/bff/auth/callback
            - name: BFF_OAUTH2_END_SESSION_URI
              value: http://localhost:8080/connect/logout
            - name: BFF_OAUTH2_LOGOUT_URI
              value: http://localhost:8080/logout
            - name: BFF_OAUTH2_SCOPE
              value: openid profile

            - name: BFF_API_COMMUNITY_ME_URI
              value: http://spring-cloud-gateway:8080/api/community/me
            - name: BFF_API_USER_ME_URI
              value: http://spring-cloud-gateway:8080/api/user/me
            - name: BFF_API_STOCK_ME_URI
              value: http://spring-cloud-gateway:8080/api/stock/me

---
apiVersion: v1
kind: Service
metadata:
  name: spring-bff-service
  namespace: spring-msa
spec:
  selector:
    app: spring-bff-service
  ports:
    - port: 8079
      targetPort: 8079

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-shell-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-shell-web
  template:
    metadata:
      labels:
        app: spring-shell-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: spring-shell-web
          image: ghcr.io/hyunmyungchoi/spring-shell-web:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: spring-shell-web
  namespace: spring-msa
spec:
  selector:
    app: spring-shell-web
  ports:
    - port: 80
      targetPort: 80