CREATE TABLE stock_watch_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_sub VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    memo VARCHAR(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_watch_owner_symbol UNIQUE (owner_sub, symbol)
);
