server:
  port: 8084

spring:
  application:
    name: spring-stock-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.stockservice: debug
    org.springframework.security: debug
