apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10-user-service.yaml
  - 13-auth-server.yaml

replicas:
  - name: spring-user-service
    count: 2
  - name: spring-security-authorization-server
    count: 1

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {}
                matchLabelKeys:
                  - pod-template-hash
                topologyKey: kubernetes.io/hostname
