apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: spring-react-msa
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: spring-react-msa/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"

            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"

            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/msa

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-react-msa-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-react-msa-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: spring-react-msa-config
                  key: REDIS_HOST

            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: spring-react-msa-config
                  key: REDIS_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: spring-react-msa
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081