server:
  port: 8084

spring:
  application:
    name: spring-member-stock-service

  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

toss:
  api:
    token-cache-key: toss:oauth:access-token
    refresh-lock-key: toss:oauth:refresh-lock

logging:
  charset:
    console: UTF-8
  level:
    com.springmsa.memberstockservice: debug
    org.springframework.security: debug
