spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    schemas: stock_service
    default-schema: stock_service

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: stock_service

toss:
  api:
    base-url: ${TOSS_API_BASE_URL}
    client-id: ${TOSS_API_CLIENT_ID}
    client-secret: ${TOSS_API_CLIENT_SECRET}
