grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  defaultDashboardsTimezone: Asia/Seoul
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localtest.me
    path: /
    pathType: Prefix
  grafana.ini:
    server:
      root_url: http://grafana.localtest.me
  persistence:
    enabled: true
    type: pvc
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway
      isDefault: false
      jsonData:
        maxLines: 1000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
