grafana:
  enabled: true
  nodeSelector:
    node-pool: platform-observability
  tolerations:
    - key: node-pool
      operator: Equal
      value: platform-observability
      effect: NoSchedule
  adminUser: admin
  defaultDashboardsTimezone: Asia/Seoul
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localtest.me
    path: /
    pathType: Prefix
  grafana.ini:
    server:
      root_url: http://grafana.localtest.me
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway
      isDefault: false
      jsonData:
        maxLines: 1000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

alertmanager:
  enabled: false

prometheusOperator:
  nodeSelector:
    node-pool: platform-observability
  tolerations:
    - key: node-pool
      operator: Equal
      value: platform-observability
      effect: NoSchedule

kube-state-metrics:
  nodeSelector:
    node-pool: platform-observability
  tolerations:
    - key: node-pool
      operator: Equal
      value: platform-observability
      effect: NoSchedule

prometheus:
  prometheusSpec:
    nodeSelector:
      node-pool: platform-observability
    tolerations:
      - key: node-pool
        operator: Equal
        value: platform-observability
        effect: NoSchedule
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
