apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-admin-users
  namespace: argocd
  labels:
    springmsa.dev/domain: admin
spec:
  project: default
  source:
    repoURL: https://github.com/hyunmyungchoi/Spring-React-MSA.git
    targetRevision: master
    path: infra/k8s/spring-msa/admin-users
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-msa
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true