apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-admin-web
  namespace: spring-msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-admin-web
  template:
    metadata:
      labels:
        app: spring-admin-web
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        node-pool: application
      containers:
        - name: spring-admin-web
          image: ghcr.io/hyunmyungchoi/spring-admin-web@sha256:8eb90daee342bc7f6913825a1bd4d8a95876c93b4dc3b899ad3394a98f756be9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-web
  namespace: spring-msa
spec:
  type: ClusterIP
  selector:
    app: spring-admin-web
  ports:
    - port: 80
      targetPort: 80
