spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: redis
      port: 6379

admin-bff:
  frontend:
    redirect-uri: http://localhost:5176

  oauth2:
    authorization-uri: http://localhost:8090/oauth2/authorize
    token-uri: http://spring-admin-gateway:8090/oauth2/token
    userinfo-uri: http://spring-admin-gateway:8090/userinfo
    client-id: admin-bff-client
    client-secret: ${ADMIN_BFF_CLIENT_SECRET:admin-bff-secret}
    redirect-uri: http://localhost:8090/admin-bff/auth/callback
    end-session-uri: http://localhost:8090/connect/logout
    scope: openid profile

  api:
    user-me-uri: http://spring-cloud-gateway:8080/api/user/me
    user-admin-users-uri: http://spring-cloud-gateway:8080/api/user/admin/users