spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      client:
        registration:
          admin-bff:
            provider: admin-auth-server
            client-id: ${ADMIN_BFF_CLIENT_ID:admin-bff-client}
            client-secret: ${ADMIN_BFF_CLIENT_SECRET:admin-bff-secret}
            authorization-grant-type: authorization_code
            redirect-uri: ${ADMIN_BFF_OAUTH2_REDIRECT_URI:http://localhost:5176/admin-bff/login/oauth2/code/admin-bff}
            scope:
              - openid
              - profile
        provider:
          admin-auth-server:
            authorization-uri: ${ADMIN_BFF_OAUTH2_AUTHORIZATION_URI:http://localhost:5176/oauth2/authorize}
            token-uri: ${ADMIN_BFF_OAUTH2_TOKEN_URI:http://spring-admin-gateway:8090/oauth2/token}
            user-info-uri: ${ADMIN_BFF_OAUTH2_USERINFO_URI:http://spring-admin-gateway:8090/userinfo}
            jwk-set-uri: ${ADMIN_BFF_OAUTH2_JWK_SET_URI:http://spring-admin-gateway:8090/oauth2/jwks}
            user-name-attribute: sub

admin-bff:
  frontend:
    redirect-uri: ${ADMIN_BFF_FRONTEND_REDIRECT_URI:http://localhost:5176}

  oauth2:
    end-session-uri: ${ADMIN_BFF_OAUTH2_END_SESSION_URI:http://localhost:5176/connect/logout}
    logout-uri: ${ADMIN_BFF_OAUTH2_LOGOUT_URI:http://localhost:5176/logout}

  api:
    user-api-base-url: ${ADMIN_BFF_API_USER_API_BASE_URL:http://spring-member-gateway:8080}
    user-internal-base-url: ${ADMIN_BFF_API_USER_INTERNAL_BASE_URL:http://spring-user-service:8081}
