spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD}

admin-bff:
  frontend:
    redirect-uri: ${ADMIN_BFF_FRONTEND_REDIRECT_URI}

  oauth2:
    authorization-uri: ${ADMIN_BFF_OAUTH2_AUTHORIZATION_URI}
    token-uri: ${ADMIN_BFF_OAUTH2_TOKEN_URI}
    userinfo-uri: ${ADMIN_BFF_OAUTH2_USERINFO_URI}
    client-id: ${ADMIN_BFF_CLIENT_ID}
    client-secret: ${ADMIN_BFF_CLIENT_SECRET}
    redirect-uri: ${ADMIN_BFF_OAUTH2_REDIRECT_URI}
    end-session-uri: ${ADMIN_BFF_OAUTH2_END_SESSION_URI}
    logout-uri: ${ADMIN_BFF_OAUTH2_LOGOUT_URI}
    scope: ${ADMIN_BFF_OAUTH2_SCOPE:openid profile}

  api:
    user-me-uri: ${ADMIN_BFF_API_USER_ME_URI}
    user-admin-users-uri: ${ADMIN_BFF_API_USER_ADMIN_USERS_URI}
    user-signup-uri: ${ADMIN_BFF_API_USER_SIGNUP_URI}

logging:
  level:
    com.springmsa.adminbff: info
