server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /bff/ {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /.well-known/ {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }

    location /oauth2/ {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }

    location /login/password {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }

    location /login/email/ {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }

    location /login/whatsapp/ {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }

    location /userinfo {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }

    location /logout {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }

    location /connect/ {
        proxy_pass http://spring-cloud-gateway:8080;
        proxy_set_header Host $host;
    }
}
